version: "3.3"

networks:
  loadbalancer-net:
    external: true
  drone:
    driver: overlay

volumes:
  dronedata:
    external: true

services:
  drone-server:
    image: drone/drone:latest
    ports:
      - "10.0.0.10:9000:9000/tcp"
    networks:
      - drone
      - loadbalancer-net
    volumes:
      - dronedata:/var/lib/drone
    configs:
      - source: drone_config
        target: /.env
    deploy:
      # placement:
      #   constraints:
      #     - node.role==worker
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        - "traefik.enable=true"
        - "traefik.port=8000"
        - "traefik.backend=ci"
        - "traefik.docker.network=loadbalancer-net"
        - "traefik.frontend.rule=Host:drone.hagen-hasenbalg.de"


  drone-agent:
    image: drone/agent:latest
    command: agent
    networks:
      - drone
    configs:
      - source: drone_config
        target: /.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      # placement:
      #   constraints:
      #     - node.role==worker
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 20s

configs:
  drone_config:
    file: ./env/.drone-env
