version: "3"

networks:
  gitea:
    external: false
  loadbalancer-net:
    external: true

volumes:
  gitea:
    driver: local

services:
  server:
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
    networks:
      - gitea
      - loadbalancer-net
    volumes:
      - ./gitea:/data
    ports:
      - "222:22"
    deploy:
      # placement:
      #   constraints:
      #     - node.role==worker
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        - "traefik.enable=true"
        - "traefik.port=3000"
        - "traefik.backend=ci"
        - "traefik.docker.network=loadbalancer-net"
        - "traefik.frontend.rule=Host:git.hagen-hasenbalg.de"
