version: '3'

volumes:
    jenkins_home:

networks:
    postgres-net:
    loadbalancer-net:
        external: true


services:
    jenkins:
        image: jenkins/jenkins:lts
        ports:
           - "8081:8080"
           - "50000:50000"
        networks:
            - loadbalancer-net
        volumes:
            - jenkins_home:/var/jenkins_home
        # environment:
        deploy:
            restart_policy:
                condition: on-failure
                delay: 10s
                max_attempts: 3
                window: 120s
            labels:
                - "traefik.backend.loadbalancer.swarm=true"
                - "traefik.port=8080"
                - "traefik.frontend.rule=Host:jenkins.v22017125338957481.megasrv.de"
                - "traefik.docker.network=loadbalancer-net"
            

