version: '3'

networks:
    internal:
        driver: overlay
        ipam:
            config:
                - subnet: 172.16.8.0/24    
    loadbalancer-net:
         external: true

volumes:
    kanboard_data:
    kanboard_plugins:
    wenkan_oauth2_proxy:
    gitlab_logs:
    gitlab_data:


services:
    kanboard:
        image: kanboard/kanboard
        volumes:
            - kanboard_data:/var/www/app/data
            - kanboard_plugins:/var/www/app/plugins
        networks:
            - loadbalancer-net
        deploy:
            labels:
                - traefik.frontend.rule=Host:kanboard.hagen-hasenbalg.de
                - traefik.docker.network=traefik
                - traefik.port=80

    cron:
        image: kanboard/kanboard
        volumes:
            - kanboard_data:/var/www/app/data
        user: nginx
        networks:
            - internal
        entrypoint: |
            bash -c 'bash -s <<EOF
                trap "break;exit" SIGHUP SIGINT SIGTERM
                while [ ! -f /var/www/html/config/config.php ]; do
                    sleep 1
                done
                while true; do
                    cd /var/www/app
                    ./cli cron
                    sleep 8h
                done
            EOF'

