version: '3.1'

networks:
    loadbalancer-net:
         external: true

services:
    traefik:
        image: traefik:v1.4.4
        command: --web --docker --docker.swarmmode --docker.watch --docker.domain=v22017125338957481.megasrv.de
        ports:
           - "80:80"
           - "8080:8080"
           - "443:443"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        # labels:
        #     - "traefik.enable=false"
        networks:
            - loadbalancer-net
        deploy:
            placement:
                constraints: [node.role == manager]
            update_config:
                parallelism: 1
                delay: 10s
            restart_policy:
                condition: on-failure
                delay: 10s
                max_attempts: 3
                window: 120s