version: '3.1'


volumes:
    postgres_db_data:


networks:
    postgres-net:
        external: true
    loadbalancer-net:
        external: true


secrets:
    postgres_password:
        external: true
    hash_key:
        external: true
    cipher_key:
        external: true
        

services:

    postgres-db:
        image: postgres
        ports:
            - "5432:5432"
        volumes:
            - postgres_db_data:/var/lib/postgresql/data
        networks:
            - postgres-net
        secrets:
            - postgres_password
        environment:
            POSTGRES_USER: waddle
            POSTGRES_DB: waddle
            POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password


    apiserver:
        image: waddle/webserver
        command: ["./wait-for-it.sh", "postgres-db:5432", "--", "docker-entrypoint.sh"] 
        # ports:
        #    - "9000:9000"
        networks:
            - postgres-net
            - loadbalancer-net
        secrets:
            - postgres_password
            - hash_key
            - cipher_key
        environment:
            POSTGRES_HOSTNAME: postgres-db
            POSTGRES_PORT: 5432
            POSTGRES_USER: vapor
            POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
            POSTGRES_DB: vapor

            HASH_KEY: /run/secrets/hash_key
            CIPHER_KEY: /run/secrets/cipher_key

        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 10s
                max_attempts: 3
                window: 120s
            update_config:
                parallelism: 1
                delay: 10s
            labels:
                traefik.enable: "true"
                traefik.frontend.passHostHeader: "true"
                traefik.backend.loadbalancer.stickiness: "true"
                traefik.backend.loadbalancer.swarm: "true"
                traefik.port: "9001"
                traefik.frontend.rule: "Host:api.v22017125338957481.megasrv.de"
                traefik.docker.network: "loadbalancer-net"


