version: '3.1'


networks:
    loadbalancer-net:
         external: true


services:
    staticContentServer:
        image: waddle/webclient:latest
        networks:
            - loadbalancer-net
        # ports:
        #     - "8888:80"
        deploy:
            # placement:
            #     constraints: [node.role == worker]
            update_config:
                parallelism: 2
                delay: 10s
            restart_policy:
                condition: on-failure
                delay: 10s
                max_attempts: 3
                window: 120s
            labels:
                - "traefik.backend.loadbalancer.swarm=true"
                - "traefik.port=80"
                - "traefik.frontend.rule=Host:waddle.hagen-hasenbalg.de"
                - "traefik.docker.network=loadbalancer-net"