version: "3.1"

volumes:
    mariadb_vol:

networks:
    mariadb:

secrets:
    wp_db_password:
        external: true
    root_db_password:
        external: true

services:

    wp:
        image: wordpress:latest
        volumes:
            - ./wordpress:/var/www/html
        secrets:
            - wp_db_password
        ports:
            - '8000:80'
        environment:
            - WORDPRESS_DB_USER=wp
            - WORDPRESS_DB_NAME=wp
            - WORDPRESS_DB_PASSWORD_FILE=/run/secrets/wp_db_password
            - WORDPRESS_DB_HOST=mariadb
        networks:
            - mariadb
        deploy:
            # placement:
            #         constraints: [node.role == worker]
            replicas: 1
            update_config:
                parallelism: 2
                delay: 10s
            restart_policy:
                condition: on-failure
            labels:
                - "traefik.backend.loadbalancer.swarm=true"
                - "traefik.port=80"
                - "traefik.frontend.rule=Host:kutsch.v22017125338957481.megasrv.de"
                - "traefik.docker.network=loadbalancer-net"
    mariadb:
            image: mariadb
            volumes:
                - mariadb_vol:/var/lib/mysql
            secrets:
                - wp_db_password
                - root_db_password
            environment:
                - MYSQL_USER=wp
                - MYSQL_DATABASE=wp
                - MYSQL_PASSWORD_FILE=/run/secrets/wp_db_password
                - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/root_db_password
            networks:
                - mariadb
            deploy:
                # placement:
                #         constraints: [node.role == manager]
                replicas: 1
                restart_policy:
                    condition: on-failure


